steps:
  - label: ":whale: Build"
    command: docker/build

  - wait

  - label: ":construction_worker: Create demo"
    command: docker/create_demo
    artifact_paths:
      - build/git
      - build/demo

  - wait

  - label: ":shipit: Push images"
    command: docker/push

  - wait

  # The next 3 steps trigger builds on the large images we use for
  # downstream work: https://buildkite.com/docs/pipelines/trigger-step
  #
  # By default these will trigger only when orderly.server is on
  # master - comment out the "branches:" key to make it always trigger
  #
  # By default these will trigger the master branch on the downstream
  # repo - change the "branch:" key to use a feature branch
  - trigger: "orderly-dot-server"
    label: ":rocket: orderly.server (from orderly) :cloud:"
    branches: "master"
    build:
      branch: master

  - trigger: "orderly-dot-server-test"
    label: ":rocket: orderly.server (from orderly) :cloud:"
    build:
      branch: !master
      env:
        ORDERLY_VERSION: "${BUILDKITE_COMMIT:0:7}"
