#!/usr/bin/env bash
set -eu

GIT_ID=$(git rev-parse --short=7 HEAD)
GIT_BRANCH=$(git symbolic-ref --short HEAD)
REGISTRY=docker.montagu.dide.ic.ac.uk:5000
NAME=orderly
PUBLIC_REGISTRY=vimc
ORDERLY_VERSION=$(grep '^Version: ' DESCRIPTION  | sed 's/Version: *//')

PRIVATE_DOCKER_TAG=$REGISTRY/$NAME
PRIVATE_DOCKER_COMMIT_TAG=$REGISTRY/$NAME:$GIT_ID
PRIVATE_DOCKER_BRANCH_TAG=$REGISTRY/$NAME:$GIT_BRANCH
PRIVATE_DOCKER_BRANCH_TAG=$REGISTRY/$NAME:$GIT_BRANCH

docker build \
       --build-arg GIT_ID=$GIT_ID \
       --build-arg GIT_BRANCH=$GIT_BRANCH \
       --build-arg ORDERLY_VERSION=$ORDERLY_VERSION \
       --tag $PRIVATE_DOCKER_COMMIT_TAG \
       --tag $PRIVATE_DOCKER_BRANCH_TAG \
       -f docker/Dockerfile .

docker push $PRIVATE_DOCKER_BRANCH_TAG
docker push $PRIVATE_DOCKER_COMMIT_TAG

if [ $GIT_BRANCH = "master" ]; then
    PUBLIC_DOCKER_COMMIT_TAG=$PUBLIC_REGISTRY/$NAME:$GIT_ID
    PUBLIC_DOCKER_BRANCH_TAG=$PUBLIC_REGISTRY/$NAME:$GIT_BRANCH
    PUBLIC_DOCKER_VERSION_TAG=$PUBLIC_REGISTRY/$NAME:v$ORDERLY_VERSION
    PRIVATE_DOCKER_VERSION_TAG=$REGISTRY/$NAME:v$ORDERLY_VERSION

    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PUBLIC_DOCKER_COMMIT_TAG
    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PUBLIC_DOCKER_BRANCH_TAG
    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PUBLIC_DOCKER_VERSION_TAG
    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PRIVATE_DOCKER_VERSION_TAG

    docker push $PUBLIC_DOCKER_COMMIT_TAG
    docker push $PUBLIC_DOCKER_BRANCH_TAG
    docker push $PUBLIC_DOCKER_VERSION_TAG
    docker push $PRIVATE_DOCKER_VERSION_TAG
fi
