#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       -t $TAG_SHA \
       -t $TAG_BRANCH \
       -t $TAG_VERSION \
       -f docker/Dockerfile \
       .

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
