#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

USER_UID=$(id -u)
USER_GID=$(id -g)
USER_STR="${USER_UID}:${USER_GID}"

DEST=build
rm -rf $DEST

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

docker run --rm --entrypoint create_orderly_demo.sh \
       --user "$USER_STR" \
       --env HOME=/tmp \
       -v "${PWD}":/orderly \
       -w /orderly \
       "$TAG_SHA" \
       "$DEST"
