#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

USER_UID=`id -u`
USER_GID=`id -g`
USER_STR="${USER_UID}:${USER_GID}"

DEST=build
rm -rf $DEST

docker run --rm --entrypoint create_orderly_demo.sh \
       --user "$USER_STR" \
       -v "${PWD}":/orderly \
       -w /orderly \
       "$TAG_SHA" \
       "$DEST"
