ARG ORDERLY_BASE
FROM $ORDERLY_BASE

RUN apt-get update && apt-get -y install --no-install-recommends \
        libcurl4-openssl-dev \
        libxml2-dev \
        zlib1g-dev \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

RUN install2.r --error \
        pkgdown

COPY . /orderly

ENTRYPOINT []
CMD ["/bin/bash"]
