#!/usr/bin/env Rscript
stopifnot(file.exists("DESCRIPTION"))

input <- readLines("vignettes/orderly.Rmd")
readme <- readLines("README.md.in")

str_from <- "<!-- introduction begin -->"
str_to <- "<!-- introduction end -->"
str_replace <- "<!-- introduction -->"
stopifnot(str_from %in% input,
          str_to %in% input,
          str_replace %in% readme)

i <- which(input == str_from) + 1
j <- which(input == str_to) - 1
k <- which(readme == str_replace)

introduction <- input[i:j]
header <- "<!-- DO NOT EDIT THIS FILE - SEE README.md.in -->"
txt <- c(header,
         readme[1:(k - 1)],
         introduction,
         readme[(k + 1):length(readme)])

writeLines(txt, "README.md")
